shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 1000.0
controller_patience: 1000.0
conservative_reset_dist: 3.0
planner_frequency: 0.5 # [Hz]
oscillation_timeout: 10.0
oscillation_distance: 0.2
